language: cpp
os: linux
compiler: clang-3.8
dist: trusty
sudo: require
addons:
  apt:
    packages:
      - clang-3.8
      - g++-5
env: CLANG_VERSION=3.8
script:
  - export CXX=clang++-$CLANG_VERSION
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="$CXX"
  - make